name: GitHub's Super Linter
 
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
 
      - uses: actions/checkout@v2
      - name: Run GitHub's Super Linter
        uses: github/super-linter@v3.15.5
        env:
              VALIDATE_ALL_CODEBASE: false
              DEFAULT_BRANCH: main
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
